[toolchain]
channel = "stable"
components = [
  "rustc",
  "rustfmt",
  "rust-src",
  "clippy",
  "rust-analyzer"
]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-linux-android",
  "armv7-linux-androideabi"
]
