//! Contains replacement SDL3 main macro
#![allow(unused)]

use sdl3_sys::{events::SDL_Event, init::SDL_AppResult};
use sdl3_main::AppResult;

/// Trait for callback-driven SDL3 applications.
///
/// Implement this trait on your application struct and call [`run`] to start
/// the SDL3 main-callbacks loop. SDL will call your methods at the appropriate
/// times; you never write a manual event/render loop.
pub trait App: Sized {
    type Error;

    /// Called once at startup. Create your window, device, and resources here.
    /// Return `Err` to abort launch.
    fn init() -> Result<Self, Self::Error>;

    /// Called once per frame.
    fn iterate(&mut self) -> AppResult;

    /// Called once per pending event.
    fn event(&mut self, event: &SDL_Event) -> AppResult;

    /// Called once before the process exits. Clean up resources here if needed
    /// (though `Drop` impls will also run).
    fn quit(&mut self) {}
}

unsafe extern "C" fn app_init<T: App>(
    appstate: *mut *mut core::ffi::c_void,
    _argc: core::ffi::c_int,
    _argv: *mut *mut core::ffi::c_char,
) -> SDL_AppResult {
    match T::init() {
        Ok(app) => {
            let boxed = Box::new(app);
            unsafe { *appstate = Box::into_raw(boxed) as *mut core::ffi::c_void };
            SDL_AppResult::CONTINUE
        }
        Err(_) => SDL_AppResult::FAILURE,
    }
}

unsafe extern "C" fn app_iterate<T: App>(
    appstate: *mut core::ffi::c_void,
) -> SDL_AppResult {
    let app = unsafe { &mut *(appstate as *mut T) };

    app.iterate().into()
}

unsafe extern "C" fn app_event<T: App>(
    appstate: *mut core::ffi::c_void,
    event: *mut SDL_Event,
) -> SDL_AppResult {
    let app = unsafe { &mut *(appstate as *mut T) };

    app.event(unsafe {  &*event }).into()
}

unsafe extern "C" fn app_quit<T: App>(
    appstate: *mut core::ffi::c_void,
    _result: SDL_AppResult,
) {
    if !appstate.is_null() {
        let mut app = unsafe { Box::from_raw(appstate as *mut T) };
        app.quit();
        // Box is dropped here, running T's Drop impl
    }
}

/// Enter the SDL3 callback-based main loop with the given argc/argv.
/// Returns the process exit code. This is the raw entry point.
///
/// # Safety
///
/// `argc` and `argv` must be valid C main arguments.
pub unsafe fn enter_main_callbacks<T: App>(
    argc: core::ffi::c_int,
    argv: *mut *mut core::ffi::c_char,
) -> core::ffi::c_int {
    // setup panic hook
    super::panic_hook::setup_panic_hook();

    unsafe {
        sdl3_sys::main::SDL_SetMainReady();
        sdl3_sys::main::SDL_EnterAppMainCallbacks(
            argc,
            argv,
            Some(app_init::<T>),
            Some(app_iterate::<T>),
            Some(app_event::<T>),
            Some(app_quit::<T>),
        )
    }
}

/// Defines entrypoint for all platforms, given type must implement [`App`]
///
/// Function (`start_sdl` by if no name is provided) on desktop, and SDL_main on android both of
/// which start SDL callbacks with the specified type
///
/// # Use default function name
/// ```ignore
/// sdl3_main!(MyApp);
/// ```
///
/// # Use custom function name 'start_gui'
/// ```ignore
/// sdl3_main!(MyApp, start_gui);
/// ```
#[macro_export]
macro_rules! sdl3_main {
    ($app:ty, $fn:ident) => {
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn SDL_main(
            argc: ::core::ffi::c_int,
            argv: *mut *mut ::core::ffi::c_char,
        ) -> ::core::ffi::c_int {
            unsafe { $crate::sdl3::callback::enter_main_callbacks::<$app>(argc, argv) }
        }

        /// Start SDL, meant to be ran from main function to allow deciding whether to open the
        /// window or not
        ///
        /// Autogenerated by `sdl3_main` macro
        pub fn $fn() -> ! {
            unsafe {
                let rc = $crate::sdl3::callback::enter_main_callbacks::<$app>(0, std::ptr::null_mut());
                std::process::exit(rc)
            }
        }
    };

    ($app:ty) => {
        crate::sdl3_main!($app, start_sdl);
    };
}
